"""Knowledge sources: the graph the graders verify answers against (spec §5)."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from truthloop.contracts.common import Direction, EntityRef, EntityType, Predicate
from truthloop.knowledge.graph import KnowledgeError


class KnowledgeSource(Protocol):
    def resolve(self, raw_id: str, entity_type: EntityType) -> EntityRef | None: ...
    def neighbors(self, program: EntityRef, direction: Direction, depth: int) -> set[EntityRef]: ...
    def programs_of(self, tables: Iterable[EntityRef]) -> set[EntityRef]: ...
    def tables_of(self, programs: Iterable[EntityRef]) -> set[EntityRef]: ...
    def has_edge(self, subject: EntityRef, predicate: Predicate, obj: EntityRef) -> bool: ...
    def has_docs(self) -> bool: ...
    def fingerprint(self) -> str: ...


__all__ = ["KnowledgeError", "KnowledgeSource"]
